@file:JvmName("PsiExported")
@file:Suppress("unused")

/*
 * file "exported.kt". DO NOT EDIT MANUALLY. THIS FILE IS GENERATED BY GRADLE.
 */

package net.notjustanna.psi.exported

/**
 * Psi Version
 */
const val psi_version = "1.2.1"